# Table of Contents

- [Assert (단언)](#assert-단언)
    - [엄격한(Strict) assertion 모드](#엄격한strict-assertion-모드)
    - [레거시 어서션 모드](#레거시-어서션-모드)
    - [클래스: assert.AssertionError[\[소스\]](https://github.com/nodejs/node/blob/d8c3089cd5bf82fddd7939a1195631ea057261e2/lib/assert.js#L179)](#클래스-assertassertionerror소스httpsgithubcomnodejsnodeblobd8c3089cd5bf82fddd7939a1195631ea057261e2libassertjsl179)
      - [`new assert.AssertionError(options)`](#new-assertassertionerroroptions)
    - [클래스: `assert.CallTracker`](#클래스-assertcalltracker)
      - [`new assert.CallTracker()`](#new-assertcalltracker)
      - [`tracker.calls([fn][, exact])`](#trackercallsfn-exact)
      - [`tracker.getCalls(fn)`](#trackergetcallsfn)
      - [`tracker.report()`](#trackerreport)
      - [`tracker.reset([fn])`](#trackerresetfn)
      - [`tracker.verify()`](#trackerverify)
    - [`assert(value[, message])`](#assertvalue-message)
    - [`assert.deepEqual(actual, expected[, message])`](#assertdeepequalactual-expected-message)
      - [비교 상세 정보](#비교-상세-정보)
    - [`assert.deepStrictEqual(actual, expected[, message])`](#assertdeepstrictequalactual-expected-message)
      - [비교 상세 정보](#비교-상세-정보)
    - [`assert.doesNotMatch(string, regexp[, message])`](#assertdoesnotmatchstring-regexp-message)
    - [`assert.doesNotReject(asyncFn[, error][, message])`](#assertdoesnotrejectasyncfn-error-message)
    - [`assert.doesNotThrow(fn[, error][, message])`](#assertdoesnotthrowfn-error-message)
    - [`assert.equal(actual, expected[, message])`](#assertequalactual-expected-message)
    - [`assert.fail([message])`](#assertfailmessage)
    - [`assert.fail(actual, expected[, message[, operator[, stackStartFn]]])`](#assertfailactual-expected-message-operator-stackstartfn)
    - [`assert.ifError(value)`](#assertiferrorvalue)
    - [`assert.match(string, regexp[, message])`](#assertmatchstring-regexp-message)
    - [`assert.notDeepEqual(actual, expected[, message])`](#assertnotdeepequalactual-expected-message)
    - [`assert.notDeepStrictEqual(actual, expected[, message])`](#assertnotdeepstrictequalactual-expected-message)
    - [`assert.notEqual(actual, expected[, message])`](#assertnotequalactual-expected-message)
    - [`assert.notStrictEqual(actual, expected[, message])`](#assertnotstrictequalactual-expected-message)
    - [`assert.ok(value[, message])`](#assertokvalue-message)
    - [`assert.rejects(asyncFn[, error][, message])`](#assertrejectsasyncfn-error-message)
    - [`assert.strictEqual(actual, expected[, message])`](#assertstrictequalactual-expected-message)
    - [`assert.throws(fn[, error][, message])`](#assertthrowsfn-error-message)
    - [`assert.partialDeepStrictEqual(actual, expected[, message])`](#assertpartialdeepstrictequalactual-expected-message)

# Assert (단언)

**소스 코드:** [lib/assert.js](https://github.com/nodejs/node/blob/v23.5.0/lib/assert.js)

`node:assert` 모듈은 불변 조건을 검증하기 위한 다양한 단언 함수를 제공합니다.


### 엄격한(Strict) assertion 모드

엄격한 assertion 모드에서는 비엄격(non-strict) 메서드들이 해당하는 엄격(strict) 메서드처럼 동작합니다. 예를 들어, [`assert.deepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepequalactual-expected-message)은 [`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)처럼 작동합니다.

엄격한 assertion 모드에서는 객체에 대한 오류 메시지가 차이점(diff)을 보여줍니다. 반면, 레거시(legacy) assertion 모드에서는 객체가 표시되며, 종종 잘려서 보입니다.

엄격한 assertion 모드를 사용하려면 다음과 같이 코드를 작성합니다:

```js
import { strict as assert } from 'node:assert';
```

또는

```js
import assert from 'node:assert/strict';
```

오류 차이점 예제:

```js
import { strict as assert } from 'node:assert';
assert.deepEqual([[[1, 2, 3]], 4, 5], [[[1, 2, '3']], 4, 5]);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// ... Lines skipped
// 
// [
//   [
//     ...
//     2,
//     + 3
//     - '3'
//   ],
//   ...
//   5
// ]
```

색상을 비활성화하려면 `NO_COLOR` 또는 `NODE_DISABLE_COLORS` 환경 변수를 사용합니다. 이렇게 하면 REPL에서도 색상이 비활성화됩니다. 터미널 환경에서 색상 지원에 대한 자세한 내용은 tty [`getColorDepth()`](https://nodejs.org/docs/latest/api/tty.html#writestreamgetcolordepthenv) 문서를 참고하세요.


### 레거시 어서션 모드[#](https://nodejs.org/docs/latest/api/assert.html#legacy-assertion-mode)

레거시 어서션 모드는 다음 메서드에서 [`==` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality)를 사용합니다:

-   [`assert.deepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepequalactual-expected-message)
-   [`assert.equal()`](https://nodejs.org/docs/latest/api/assert.html#assertequalactual-expected-message)
-   [`assert.notDeepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertnotdeepequalactual-expected-message)
-   [`assert.notEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertnotequalactual-expected-message)

레거시 어서션 모드를 사용하려면 다음과 같이 작성합니다:

```js
import assert from 'node:assert';
```

레거시 어서션 모드는 예상치 못한 결과를 초래할 수 있습니다. 특히 [`assert.deepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepequalactual-expected-message)을 사용할 때 주의가 필요합니다:

```js
// 주의: 이 코드는 레거시 어서션 모드에서 AssertionError를 발생시키지 않습니다!
assert.deepEqual(/a/gi, new Date());
```


### 클래스: assert.AssertionError[\[소스\]](https://github.com/nodejs/node/blob/d8c3089cd5bf82fddd7939a1195631ea057261e2/lib/assert.js#L179)[#](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)

-   상속: [`<errors.Error>`](https://nodejs.org/docs/latest/api/errors.html#class-error)

`AssertionError` 클래스는 **어설션(assertion)의 실패**를 나타냅니다. `node:assert` 모듈에서 발생하는 모든 에러는 `AssertionError` 클래스의 인스턴스입니다.


#### `new assert.AssertionError(options)`[#](https://nodejs.org/docs/latest/api/assert.html#new-assertassertionerroroptions)

추가된 버전: v0.1.21

-   `options` [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
    -   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) 제공된 경우, 에러 메시지가 이 값으로 설정된다.
    -   `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) 에러 인스턴스의 `actual` 속성.
    -   `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) 에러 인스턴스의 `expected` 속성.
    -   `operator` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) 에러 인스턴스의 `operator` 속성.
    -   `stackStartFn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) 제공된 경우, 생성된 스택 트레이스에서 이 함수 이전의 프레임을 생략한다.

`Error`의 하위 클래스로, **어설션(assertion) 실패**를 나타낸다.

모든 인스턴스는 내장 `Error` 속성(`message`와 `name`)을 포함하며, 추가로 다음 속성을 가진다:

-   `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) [`assert.strictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertstrictequalactual-expected-message)과 같은 메서드의 `actual` 인자로 설정된다.
-   `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) [`assert.strictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertstrictequalactual-expected-message)과 같은 메서드의 `expected` 값으로 설정된다.
-   `generatedMessage` [`<boolean>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) 메시지가 자동 생성되었는지(`true`) 여부를 나타낸다.
-   `code` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) 에러가 어설션 에러임을 나타내기 위해 항상 `ERR_ASSERTION`으로 설정된다.
-   `operator` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) 전달된 연산자 값으로 설정된다.

```js
import assert from 'node:assert';

// 나중에 에러 메시지를 비교하기 위해 AssertionError 생성
const { message } = new assert.AssertionError({
    actual: 1,
    expected: 2,
    operator: 'strictEqual',
});

// 에러 출력 검증
try {
    assert.strictEqual(1, 2);
} catch (err) {
    assert(err instanceof assert.AssertionError);
    assert.strictEqual(err.message, message);
    assert.strictEqual(err.name, 'AssertionError');
    assert.strictEqual(err.actual, 1);
    assert.strictEqual(err.expected, 2);
    assert.strictEqual(err.code, 'ERR_ASSERTION');
    assert.strictEqual(err.operator, 'strictEqual');
    assert.strictEqual(err.generatedMessage, true);
}
```


### 클래스: `assert.CallTracker`[#](https://nodejs.org/docs/latest/api/assert.html#class-assertcalltracker)

이 기능은 더 이상 사용되지 않으며(deprecated), 향후 버전에서 제거될 예정입니다. 대신 [`mock`](https://nodejs.org/docs/latest/api/test.html#mocking) 헬퍼 함수와 같은 대안을 사용하는 것을 고려해 보세요.


#### `new assert.CallTracker()`[#](https://nodejs.org/docs/latest/api/assert.html#new-assertcalltracker)

추가된 버전: v14.2.0, v12.19.0

특정 함수가 정확한 횟수만큼 호출되었는지 추적할 수 있는 [`CallTracker`](https://nodejs.org/docs/latest/api/assert.html#class-assertcalltracker) 객체를 생성합니다. 검증을 수행하려면 `tracker.verify()`를 호출해야 합니다. 일반적으로 이 메서드는 [`process.on('exit')`](https://nodejs.org/docs/latest/api/process.html#event-exit) 핸들러에서 호출됩니다.

```js
import assert from 'node:assert';
import process from 'node:process';

const tracker = new assert.CallTracker();

function func() {}

// func() 함수는 tracker.verify() 호출 전에 정확히 1번 호출되어야 합니다.
const callsfunc = tracker.calls(func, 1);

callsfunc();

// tracker.verify()를 호출하여 모든 tracker.calls() 함수가 정확한 횟수만큼 호출되었는지 검증합니다.
process.on('exit', () => {
    tracker.verify();
});
```


#### `tracker.calls([fn][, exact])`[#](https://nodejs.org/docs/latest/api/assert.html#trackercallsfn-exact)

추가된 버전: v14.2.0, v12.19.0

-   `fn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) **기본값:** 아무 작업도 하지 않는 함수.
-   `exact` [`<number>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) **기본값:** `1`.
-   반환값: [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) `fn`을 감싸는 함수.

이 래퍼 함수는 정확히 `exact` 횟수만큼 호출될 것으로 예상됩니다. [`tracker.verify()`](https://nodejs.org/docs/latest/api/assert.html#trackerverify)가 호출될 때 함수가 정확히 `exact` 횟수만큼 호출되지 않았다면, [`tracker.verify()`](https://nodejs.org/docs/latest/api/assert.html#trackerverify)는 에러를 발생시킵니다.

```js
import assert from 'node:assert';

// 호출 추적기 생성
const tracker = new assert.CallTracker();

function func() {}

// tracker.verify()가 호출되기 전에 정확히 exact 횟수만큼 호출되어야 하는 func()를 감싸는 함수 반환
const callsfunc = tracker.calls(func);
```


#### `tracker.getCalls(fn)`[#](https://nodejs.org/docs/latest/api/assert.html#trackergetcallsfn)

추가된 버전: v18.8.0, v16.18.0

-   `fn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)
    
-   반환값: [`<Array>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) 추적된 함수에 대한 모든 호출을 담은 배열
    
-   객체 [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
    
    -   `thisArg` [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
    -   `arguments` [`<Array>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) 추적된 함수에 전달된 인자들

```js
import assert from 'node:assert';

const tracker = new assert.CallTracker();
function func() {}

const callsfunc = tracker.calls(func);
callsfunc(1, 2, 3);

assert.deepStrictEqual(tracker.getCalls(callsfunc), [
  { thisArg: undefined, arguments: [1, 2, 3] }
]);
```


#### `tracker.report()`[#](https://nodejs.org/docs/latest/api/assert.html#trackerreport)

추가된 버전: v14.2.0, v12.19.0

-   반환값: [`<Array>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array) [`tracker.calls()`](https://nodejs.org/docs/latest/api/assert.html#trackercallsfn-exact)에서 반환된 래퍼 함수에 대한 정보를 담은 객체 배열.
-   객체 [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)
    -   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)
    -   `actual` [`<number>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) 함수가 실제로 호출된 횟수.
    -   `expected` [`<number>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) 함수가 예상된 횟수만큼 호출되어야 하는 횟수.
    -   `operator` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) 래핑된 함수의 이름.
    -   `stack` [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) 함수의 스택 트레이스.

이 배열은 예상된 횟수만큼 호출되지 않은 함수들에 대한 예상 호출 횟수와 실제 호출 횟수 정보를 포함합니다.

```js
import assert from 'node:assert';

// 호출 트래커 생성
const tracker = new assert.CallTracker();

function func() {}

// func()를 래핑한 함수를 반환하며, 이 함수는 tracker.verify() 전에 정확한 횟수만큼 호출되어야 함
const callsfunc = tracker.calls(func, 2);

// callsfunc()에 대한 정보를 담은 배열 반환
console.log(tracker.report());
// [
//   {
//     message: 'Expected the func function to be executed 2 time(s) but was executed 0 time(s).',
//     actual: 0,
//     expected: 2,
//     operator: 'func',
//     stack: stack trace
//   }
// ]
```


#### `tracker.reset([fn])`[#](https://nodejs.org/docs/latest/api/assert.html#trackerresetfn)

추가된 버전: v18.8.0, v16.18.0

-   `fn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) 초기화할 추적된 함수

호출 추적기의 호출 기록을 초기화합니다. 인자로 추적된 함수를 전달하면 해당 함수의 호출 기록만 초기화됩니다. 인자를 전달하지 않으면 모든 추적된 함수의 호출 기록이 초기화됩니다.

```js
import assert from 'node:assert';

const tracker = new assert.CallTracker();

function func() {}

const callsfunc = tracker.calls(func);
callsfunc(); // 추적기가 한 번 호출됨
assert.strictEqual(tracker.getCalls(callsfunc).length, 1);

tracker.reset(callsfunc);
assert.strictEqual(tracker.getCalls(callsfunc).length, 0);
```


#### `tracker.verify()`[#](https://nodejs.org/docs/latest/api/assert.html#trackerverify)

추가된 버전: v14.2.0, v12.19.0

[`tracker.calls()`](https://nodejs.org/docs/latest/api/assert.html#trackercallsfn-exact)에 전달된 함수 목록을 순회하며, 예상된 횟수만큼 호출되지 않은 함수에 대해 에러를 발생시킵니다.

```js
import assert from 'node:assert';

// 호출 추적기를 생성합니다.
const tracker = new assert.CallTracker();

function func() {}

// func()를 감싸는 함수를 반환하며, 이 함수는 tracker.verify()가 호출되기 전에 정확한 횟수만큼 호출되어야 합니다.
const callsfunc = tracker.calls(func, 2);

callsfunc();

// callsfunc()가 한 번만 호출되었기 때문에 에러가 발생합니다.
tracker.verify();
```


### `assert(value[, message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertvalue-message)

추가된 버전: v0.5.9

-   `value` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types) 참 같은 값(truthy)인지 확인할 입력값
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

[`assert.ok()`](https://nodejs.org/docs/latest/api/assert.html#assertokvalue-message)의 별칭입니다.


### `assert.deepEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**엄격한 검증 모드(Strict assertion mode)**

[`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)의 별칭입니다.

**레거시 검증 모드(Legacy assertion mode)**

`actual`과 `expected` 매개변수 간의 깊은 동등성을 검사합니다. 대신 [`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)을 사용하는 것을 권장합니다. [`assert.deepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepequalactual-expected-message)은 예상치 못한 결과를 초래할 수 있습니다.

*깊은 동등성(Deep equality)*이란, 자식 객체의 열거 가능한 "자체" 속성들도 다음 규칙에 따라 재귀적으로 평가된다는 것을 의미합니다.


#### 비교 상세 정보

- **기본 값(Primitive values)**은 `NaN`을 제외하고 [`==` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality)로 비교됩니다. 단, 양쪽 모두 `NaN`인 경우 동일한 것으로 처리됩니다.
- **객체의 타입 태그(Type tags)**는 동일해야 합니다.
- **열거 가능한 "자체" 속성(Enumerable "own" properties)**만 고려됩니다.
- **`Error`**의 이름, 메시지, 원인, 그리고 에러는 열거 가능한 속성이 아니더라도 항상 비교됩니다.
- **객체 래퍼(Object wrappers)**는 객체로도, 래핑이 해제된 값으로도 비교됩니다.
- **`Object`**의 속성은 순서 없이 비교됩니다.
- **`Map`**의 키와 **`Set`**의 항목은 순서 없이 비교됩니다.
- **재귀(Recursion)**는 양쪽이 다르거나 양쪽이 순환 참조를 만나면 중단됩니다.
- **구현(Implementation)**은 객체의 **`[[Prototype]]`**을 테스트하지 않습니다.
- **`Symbol`** 속성은 비교되지 않습니다.
- **`WeakMap`**과 **`WeakSet`**의 비교는 값이 아닌 인스턴스에만 의존합니다.
- **`RegExp`**의 `lastIndex`, `flags`, `source`는 열거 가능한 속성이 아니더라도 항상 비교됩니다.

다음 예제는 기본 값이 [`==` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality)로 비교되기 때문에 **`AssertionError`**를 발생시키지 않습니다.

```js
import assert from 'node:assert'; // 주의: 이 코드는 AssertionError를 발생시키지 않습니다!
assert.deepEqual('+00000000', false);
```

**"깊은" 동등성(Deep equality)**은 자식 객체의 열거 가능한 "자체" 속성도 평가한다는 의미입니다.

```js
import assert from 'node:assert';

const obj1 = { a: { b: 1 } };
const obj2 = { a: { b: 2 } };
const obj3 = { a: { b: 1 } };
const obj4 = { __proto__: obj1 };

assert.deepEqual(obj1, obj1); // 통과
// b의 값이 다릅니다:
assert.deepEqual(obj1, obj2); // AssertionError: { a: { b: 1 } } deepEqual { a: { b: 2 } }
assert.deepEqual(obj1, obj3); // 통과
// 프로토타입은 무시됩니다:
assert.deepEqual(obj1, obj4); // AssertionError: { a: { b: 1 } } deepEqual {}
```

값이 동일하지 않으면 **`AssertionError`**가 발생하며, `message` 속성은 `message` 매개변수의 값으로 설정됩니다. `message` 매개변수가 정의되지 않은 경우 기본 오류 메시지가 할당됩니다. `message` 매개변수가 **`Error`**의 인스턴스인 경우, **`AssertionError`** 대신 해당 에러가 발생합니다.


### `assert.deepStrictEqual(actual, expected[, message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)

-   `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`actual`과 `expected` 매개변수 간의 **깊은 동등성**을 테스트합니다. "깊은" 동등성이란, 자식 객체의 열거 가능한 "자체" 속성들이 다음 규칙에 따라 재귀적으로 평가된다는 의미입니다.


#### 비교 상세 정보

- **원시 값**은 `Object.is()`를 사용하여 비교됩니다.
- 객체의 **타입 태그**는 동일해야 합니다.
- 객체의 `[[Prototype]]`은 `===` 연산자를 사용하여 비교됩니다.
- **열거 가능한 "자체" 속성**만 고려됩니다.
- `Error`의 이름, 메시지, 원인 및 에러는 열거 가능한 속성이 아니더라도 항상 비교됩니다. `errors`도 비교 대상입니다.
- 열거 가능한 자체 `Symbol` 속성도 비교됩니다.
- **객체 래퍼**는 객체와 언래핑된 값 모두로 비교됩니다.
- `Object` 속성은 순서 없이 비교됩니다.
- `Map` 키와 `Set` 항목은 순서 없이 비교됩니다.
- 양쪽이 다르거나 양쪽이 순환 참조를 만나면 재귀가 중단됩니다.
- `WeakMap`과 `WeakSet` 비교는 값에 의존하지 않습니다. 자세한 내용은 아래를 참고하세요.
- `RegExp`의 `lastIndex`, `flags`, `source`는 열거 가능한 속성이 아니더라도 항상 비교됩니다.

```js
import assert from 'node:assert/strict';

// 1 !== '1'이므로 실패
assert.deepStrictEqual({ a: 1 }, { a: '1' });
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// {
// + a: 1
// - a: '1'
// }

// 다음 객체들은 자체 속성이 없음
const date = new Date();
const object = {};
const fakeDate = {};
Object.setPrototypeOf(fakeDate, Date.prototype);

// 다른 [[Prototype]]:
assert.deepStrictEqual(object, fakeDate);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// + {}
// - Date {}

// 다른 타입 태그:
assert.deepStrictEqual(date, fakeDate);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// + 2018-04-26T00:49:08.604Z
// - Date {}

// Object.is(NaN, NaN)은 true이므로 성공
assert.deepStrictEqual(NaN, NaN);

// 다른 언래핑된 숫자:
assert.deepStrictEqual(new Number(1), new Number(2));
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// + [Number: 1]
// - [Number: 2]

// 객체와 문자열이 언래핑 시 동일하므로 성공
assert.deepStrictEqual(new String('foo'), Object('foo'));

// -0 === -0이므로 성공
assert.deepStrictEqual(-0, -0);

// 다른 제로:
assert.deepStrictEqual(0, -0);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// + 0
// - -0

const symbol1 = Symbol();
const symbol2 = Symbol();

// 동일한 심볼이므로 성공
assert.deepStrictEqual({ [symbol1]: 1 }, { [symbol1]: 1 });

// 다른 심볼이므로 실패
assert.deepStrictEqual({ [symbol1]: 1 }, { [symbol2]: 1 });
// AssertionError [ERR_ASSERTION]: Inputs identical but not reference equal:
// {
// [Symbol()]: 1
// }

const weakMap1 = new WeakMap();
const weakMap2 = new WeakMap([[{}, {}]]);
const weakMap3 = new WeakMap();
weakMap3.unequal = true;

// WeakMap 항목을 비교할 수 없으므로 성공
assert.deepStrictEqual(weakMap1, weakMap2);

// weakMap3에 weakMap1에 없는 속성이 있으므로 실패
assert.deepStrictEqual(weakMap1, weakMap3);
// AssertionError: Expected inputs to be strictly deep-equal:
// + actual - expected
// WeakMap {
// + [items unknown]
// - [items unknown],
// - unequal: true
// }
```

값이 동일하지 않으면 `message` 속성이 `message` 매개변수 값으로 설정된 `AssertionError`가 발생합니다. `message` 매개변수가 정의되지 않으면 기본 오류 메시지가 할당됩니다. `message` 매개변수가 `Error` 인스턴스인 경우 `AssertionError` 대신 해당 오류가 발생합니다.


### `assert.doesNotMatch(string, regexp[, message])`

- `string` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)
- `regexp` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`string` 입력값이 정규식과 일치하지 않을 것을 기대합니다.

```javascript
import assert from 'node:assert/strict';

assert.doesNotMatch('I will fail', /fail/); 
// AssertionError [ERR_ASSERTION]: 입력값이 정규식과 일치하지 않을 것으로 예상되었습니다.

assert.doesNotMatch(123, /pass/); 
// AssertionError [ERR_ASSERTION]: "string" 인자는 문자열 타입이어야 합니다.

assert.doesNotMatch('I will pass', /different/); 
// 통과
```

값이 일치하거나 `string` 인자가 문자열 타입이 아닌 경우, `message` 매개변수의 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않은 경우, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스인 경우, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 대신 해당 오류가 발생합니다.


### `assert.doesNotReject(asyncFn[, error][, message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertdoesnotrejectasyncfn-error-message)

추가된 버전: v10.0.0

-   `asyncFn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) | [`<Promise>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
-   `error` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) | [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)

`asyncFn`이 Promise인 경우 이를 기다리고, 함수인 경우 즉시 호출한 후 반환된 Promise가 완료될 때까지 기다립니다. 그런 다음 Promise가 거부되지 않았는지 확인합니다.

`asyncFn`이 함수이고 동기적으로 오류를 던지면, `assert.doesNotReject()`는 해당 오류와 함께 거부된 Promise를 반환합니다. 함수가 Promise를 반환하지 않으면, `assert.doesNotReject()`는 [`ERR_INVALID_RETURN_VALUE`](https://nodejs.org/docs/latest/api/errors.html#err_invalid_return_value) 오류와 함께 거부된 Promise를 반환합니다. 두 경우 모두 오류 핸들러는 건너뜁니다.

`assert.doesNotReject()`를 사용하는 것은 실제로 유용하지 않습니다. 거부를 잡은 후 다시 거부하는 데는 거의 이점이 없기 때문입니다. 대신, 거부되지 않아야 하는 특정 코드 경로 옆에 주석을 추가하고 오류 메시지를 가능한 한 명확하게 유지하는 것을 고려해보세요.

`error`가 지정된 경우, [`Class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), 또는 검증 함수일 수 있습니다. 자세한 내용은 [`assert.throws()`](https://nodejs.org/docs/latest/api/assert.html#assertthrowsfn-error-message)를 참조하세요.

비동기적으로 완료를 기다리는 점을 제외하면 [`assert.doesNotThrow()`](https://nodejs.org/docs/latest/api/assert.html#assertdoesnotthrowfn-error-message)와 동일하게 동작합니다.

```javascript
import assert from 'node:assert/strict';

await assert.doesNotReject(
    async () => {
        throw new TypeError('Wrong value');
    },
    SyntaxError
);
```

```javascript
import assert from 'node:assert/strict';

assert.doesNotReject(Promise.reject(new TypeError('Wrong value')))
    .then(() => {
        // ...
    });
```


### `assert.doesNotThrow(fn[, error][, message])`

-   `fn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)
-   `error` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) | [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)

`assert.doesNotThrow()`는 함수 `fn`이 에러를 던지지 않는다고 단언합니다.

`assert.doesNotThrow()`를 사용하는 것은 실제로 유용하지 않습니다. 에러를 잡은 후 다시 던지는 것에는 이점이 없기 때문입니다. 대신, 에러를 던지지 않아야 하는 특정 코드 경로 옆에 주석을 추가하고, 에러 메시지를 가능한 한 명확하게 유지하는 것을 고려해보세요.

`assert.doesNotThrow()`가 호출되면, `fn` 함수를 즉시 실행합니다.

만약 에러가 발생하고 그 에러가 `error` 매개변수로 지정된 타입과 동일하다면, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. 에러가 다른 타입이거나 `error` 매개변수가 정의되지 않았다면, 에러는 호출자에게 다시 전파됩니다.

`error`는 [`Class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), 또는 검증 함수로 지정할 수 있습니다. 자세한 내용은 [`assert.throws()`](https://nodejs.org/docs/latest/api/assert.html#assertthrowsfn-error-message)를 참조하세요.

예를 들어, 다음 코드는 `TypeError`가 발생하지만 단언에서 일치하는 에러 타입이 없기 때문에 `TypeError`를 던집니다:

```js
import assert from 'node:assert/strict';

assert.doesNotThrow(
    () => {
        throw new TypeError('Wrong value');
    },
    SyntaxError
);
```

반면, 다음 코드는 '원치 않는 예외가 발생했습니다...'라는 메시지와 함께 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)를 발생시킵니다:

```js
import assert from 'node:assert/strict';

assert.doesNotThrow(
    () => {
        throw new TypeError('Wrong value');
    },
    TypeError
);
```

만약 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생하고 `message` 매개변수에 값이 제공되었다면, `message`의 값은 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 메시지에 추가됩니다:

```js
import assert from 'node:assert/strict';

assert.doesNotThrow(
    () => {
        throw new TypeError('Wrong value');
    },
    /Wrong value/,
    'Whoops'
); // Throws: AssertionError: Got unwanted exception: Whoops
```


### `assert.equal(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**엄격한 검증 모드(Strict assertion mode)**

[`assert.strictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertstrictequalactual-expected-message)의 별칭입니다.

**기존 검증 모드(Legacy assertion mode)**

`actual`과 `expected` 매개변수 간의 얕은 비교를 수행하며, [`==` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality)를 사용합니다. `NaN`은 특별히 처리되며, 양쪽 모두 `NaN`인 경우 동일한 것으로 간주됩니다.

```javascript
import assert from 'node:assert';

assert.equal(1, 1); // 통과, 1 == 1
assert.equal(1, '1'); // 통과, 1 == '1'
assert.equal(NaN, NaN); // 통과
assert.equal(1, 2); // AssertionError: 1 == 2
assert.equal({ a: { b: 1 } }, { a: { b: 1 } }); // AssertionError: { a: { b: 1 } } == { a: { b: 1 } }
```

값이 동일하지 않으면 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생하며, `message` 매개변수 값이 `message` 속성으로 설정됩니다. `message` 매개변수가 정의되지 않은 경우 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error) 인스턴스인 경우, `AssertionError` 대신 해당 오류가 발생합니다.


### `assert.fail([message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertfailmessage)

추가된 버전: v0.1.21

-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) **기본값:** `'Failed'`

제공된 에러 메시지 또는 기본 에러 메시지와 함께 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)를 발생시킵니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스라면, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 대신 해당 에러가 발생합니다.

```js
import assert from 'node:assert/strict';

assert.fail(); // AssertionError [ERR_ASSERTION]: Failed
assert.fail('boom'); // AssertionError [ERR_ASSERTION]: boom
assert.fail(new TypeError('need array')); // TypeError: need array
```

`assert.fail()`을 두 개 이상의 인자와 함께 사용하는 것도 가능하지만, 이는 더 이상 권장되지 않습니다. 자세한 내용은 아래를 참고하세요.


### `assert.fail(actual, expected[, message[, operator[, stackStartFn]]])`[#](https://nodejs.org/docs/latest/api/assert.html#assertfailactual-expected-message-operator-stackstartfn)

[안정성: 0](https://nodejs.org/docs/latest/api/documentation.html#stability-index) - 사용 중단: 대신 `assert.fail([message])`나 다른 assert 함수를 사용하세요.

-   `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)
-   `operator` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) **기본값:** `'!='`
-   `stackStartFn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) **기본값:** `assert.fail`

`message`가 falsy 값이면, 에러 메시지는 `actual`과 `expected` 값을 제공된 `operator`로 구분하여 설정됩니다. 만약 `actual`과 `expected` 두 인자만 제공되면, `operator`는 기본값 `'!='`로 설정됩니다. `message`가 세 번째 인자로 제공되면, 이 메시지가 에러 메시지로 사용되고 다른 인자들은 발생한 객체의 속성으로 저장됩니다. `stackStartFn`이 제공되면, 해당 함수 위의 모든 스택 프레임이 스택 트레이스에서 제거됩니다 ([`Error.captureStackTrace`](https://nodejs.org/docs/latest/api/errors.html#errorcapturestacktracetargetobject-constructoropt) 참조). 인자가 전혀 제공되지 않으면, 기본 메시지 `Failed`가 사용됩니다.

```js
import assert from 'node:assert/strict';

assert.fail('a', 'b'); // AssertionError [ERR_ASSERTION]: 'a' != 'b'
assert.fail(1, 2, undefined, '>'); // AssertionError [ERR_ASSERTION]: 1 > 2
assert.fail(1, 2, 'fail'); // AssertionError [ERR_ASSERTION]: fail
assert.fail(1, 2, 'whoops', '>'); // AssertionError [ERR_ASSERTION]: whoops
assert.fail(1, 2, new TypeError('need array')); // TypeError: need array
```

마지막 세 경우에서 `actual`, `expected`, `operator`는 에러 메시지에 영향을 미치지 않습니다.

예외의 스택 트레이스를 줄이기 위해 `stackStartFn`을 사용하는 예제:

```js
import assert from 'node:assert/strict';

function suppressFrame() {
    assert.fail('a', 'b', undefined, '!==', suppressFrame);
}

suppressFrame();
// AssertionError [ERR_ASSERTION]: 'a' !== 'b'
// at repl:1:1
// at ContextifyScript.Script.runInThisContext (vm.js:44:33)
// ...
```


### `assert.ifError(value)`

- `value` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)

`value`가 `undefined`나 `null`이 아닌 경우, `value`를 던집니다. 이 함수는 콜백 함수의 `error` 인자를 테스트할 때 유용합니다. 스택 트레이스는 `ifError()`에 전달된 오류의 모든 프레임을 포함하며, `ifError()` 자체의 새로운 프레임도 포함될 수 있습니다.

```javascript
import assert from 'node:assert/strict';

assert.ifError(null); // OK
assert.ifError(0); // AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 0
assert.ifError('error'); // AssertionError [ERR_ASSERTION]: ifError got unwanted exception: 'error'
assert.ifError(new Error()); // AssertionError [ERR_ASSERTION]: ifError got unwanted exception: Error

// 랜덤 오류 프레임 생성
let err;
(function errorFrame() {
    err = new Error('test error');
})();

(function ifErrorFrame() {
    assert.ifError(err);
})(); // AssertionError [ERR_ASSERTION]: ifError got unwanted exception: test error
// at ifErrorFrame
// at errorFrame
```


### `assert.match(string, regexp[, message])`

- `string` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)
- `regexp` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`string` 입력값이 정규식과 일치할 것으로 기대합니다.

```javascript
import assert from 'node:assert/strict';

assert.match('I will fail', /pass/); // AssertionError [ERR_ASSERTION]: 입력값이 정규식과 일치하지 않습니다.
assert.match(123, /pass/); // AssertionError [ERR_ASSERTION]: "string" 인자는 문자열 타입이어야 합니다.
assert.match('I will pass', /pass/); // 통과
```

값이 일치하지 않거나 `string` 인자가 문자열 타입이 아닌 경우, `message` 매개변수 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않은 경우, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error) 인스턴스인 경우, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 대신 해당 오류가 발생합니다.


### `assert.notDeepEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**엄격한 검증 모드(Strict assertion mode)**

[`assert.notDeepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertnotdeepstrictequalactual-expected-message)의 별칭입니다.

**레거시 검증 모드(Legacy assertion mode)**

깊은 비교를 통해 두 값이 다른지 확인합니다. [`assert.deepEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepequalactual-expected-message)과 반대 기능을 수행합니다.

```javascript
import assert from 'node:assert';

const obj1 = { a: { b: 1 } };
const obj2 = { a: { b: 2 } };
const obj3 = { a: { b: 1 } };
const obj4 = { __proto__: obj1 };

assert.notDeepEqual(obj1, obj1); // AssertionError: { a: { b: 1 } } notDeepEqual { a: { b: 1 } }
assert.notDeepEqual(obj1, obj2); // 통과
assert.notDeepEqual(obj1, obj3); // AssertionError: { a: { b: 1 } } notDeepEqual { a: { b: 1 } }
assert.notDeepEqual(obj1, obj4); // 통과
```

두 값이 깊게 동일한 경우, `message` 매개변수 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않은 경우, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error) 인스턴스인 경우, `AssertionError` 대신 해당 오류가 발생합니다.


### `assert.notDeepStrictEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

이 함수는 두 값이 깊고 엄격하게 동일하지 않은지 테스트합니다. [`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)의 반대 기능을 수행합니다.

```javascript
import assert from 'node:assert/strict';
assert.notDeepStrictEqual({ a: 1 }, { a: '1' }); // 통과
```

만약 두 값이 깊고 엄격하게 동일하다면, `message` 매개변수 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않은 경우, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스라면, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 대신 해당 오류가 발생합니다.


### `assert.notEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

**엄격한 검증 모드(Strict assertion mode)**

[`assert.notStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertnotstrictequalactual-expected-message)의 별칭입니다.

**기존 검증 모드(Legacy assertion mode)**

[`!=` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Inequality)를 사용하여 얕은 비교와 강제 형 변환을 통해 불일치를 검증합니다. `NaN`은 특별히 처리되며, 양쪽 모두 `NaN`인 경우 동일한 것으로 간주됩니다.

```javascript
import assert from 'node:assert';

assert.notEqual(1, 2); // 통과
assert.notEqual(1, 1); // AssertionError: 1 != 1
assert.notEqual(1, '1'); // AssertionError: 1 != '1'
```

값이 동일한 경우, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생하며, `message` 속성은 `message` 인자로 전달된 값으로 설정됩니다. `message` 인자가 정의되지 않은 경우, 기본 오류 메시지가 할당됩니다. `message` 인자가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스인 경우, `AssertionError` 대신 해당 오류가 발생합니다.


### `assert.notStrictEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`actual`과 `expected` 매개변수가 [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)를 기준으로 엄격하게 같지 않은지 테스트합니다.

```javascript
import assert from 'node:assert/strict';

assert.notStrictEqual(1, 2); // 통과
assert.notStrictEqual(1, 1); // AssertionError [ERR_ASSERTION]: "actual"이 "expected"와 엄격하게 같지 않아야 합니다:
                             // 1
assert.notStrictEqual(1, '1'); // 통과
```

만약 두 값이 엄격하게 같다면, `message` 매개변수 값이 설정된 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않았다면, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스라면, `AssertionError` 대신 해당 오류가 발생합니다.


### `assert.ok(value[, message])`

- `value` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`value`가 참 같은 값(truthy)인지 테스트합니다. 이는 `assert.equal(!!value, true, message)`와 동일합니다.

`value`가 참 같은 값이 아니라면, `message` 매개변수의 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 `undefined`라면 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스라면 `AssertionError` 대신 해당 오류가 발생합니다. 아무런 인수가 전달되지 않으면 `message`는 ``'No value argument passed to `assert.ok()`'`` 문자열로 설정됩니다.

`repl`에서 발생하는 오류 메시지는 파일에서 발생하는 오류 메시지와 다르다는 점에 유의하세요. 자세한 내용은 아래를 참고하세요.

```javascript
import assert from 'node:assert/strict';

assert.ok(true); // 통과
assert.ok(1); // 통과
assert.ok(); // AssertionError: No value argument passed to `assert.ok()`
assert.ok(false, 'it\'s false'); // AssertionError: it's false

// repl에서:
assert.ok(typeof 123 === 'string'); // AssertionError: false == true

// 파일에서 (예: test.js):
assert.ok(typeof 123 === 'string'); // AssertionError: The expression evaluated to a falsy value:
                                    //
                                    // assert.ok(typeof 123 === 'string')
assert.ok(false); // AssertionError: The expression evaluated to a falsy value:
                  //
                  // assert.ok(false)
assert.ok(0); // AssertionError: The expression evaluated to a falsy value:
              //
              // assert.ok(0)
```

```javascript
import assert from 'node:assert/strict';

// `assert()`를 사용해도 동일하게 동작합니다:
assert(0); // AssertionError: The expression evaluated to a falsy value:
           //
           // assert(0)
```


### `assert.rejects(asyncFn[, error][, message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertrejectsasyncfn-error-message)

추가된 버전: v10.0.0

-   `asyncFn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) | [`<Promise>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise)
-   `error` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) | [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) | [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)

`asyncFn`이 Promise라면 완료될 때까지 기다립니다. 만약 `asyncFn`이 함수라면 즉시 호출하고 반환된 Promise가 완료될 때까지 기다립니다. 그런 다음 Promise가 거부되었는지 확인합니다.

`asyncFn`이 함수이고 동기적으로 오류를 던지면, `assert.rejects()`는 해당 오류와 함께 거부된 Promise를 반환합니다. 함수가 Promise를 반환하지 않으면, `assert.rejects()`는 [`ERR_INVALID_RETURN_VALUE`](https://nodejs.org/docs/latest/api/errors.html#err_invalid_return_value) 오류와 함께 거부된 Promise를 반환합니다. 두 경우 모두 오류 핸들러는 건너뜁니다.

비동기적으로 완료를 기다리는 점을 제외하면 [`assert.throws()`](https://nodejs.org/docs/latest/api/assert.html#assertthrowsfn-error-message)와 동일하게 동작합니다.

`error`가 지정되면, [`Class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), 검증 함수, 각 속성이 테스트될 객체, 또는 `message`와 `name` 속성을 포함한 오류 인스턴스가 될 수 있습니다.

`message`가 지정되면, `asyncFn`이 거부되지 않을 때 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 제공하는 메시지가 됩니다.

```javascript
import assert from 'node:assert/strict';

await assert.rejects(
    async () => {
        throw new TypeError('Wrong value');
    },
    {
        name: 'TypeError',
        message: 'Wrong value',
    }
);
```

```javascript
import assert from 'node:assert/strict';

await assert.rejects(
    async () => {
        throw new TypeError('Wrong value');
    },
    (err) => {
        assert.strictEqual(err.name, 'TypeError');
        assert.strictEqual(err.message, 'Wrong value');
        return true;
    }
);
```

```javascript
import assert from 'node:assert/strict';

assert.rejects(
    Promise.reject(new Error('Wrong value')),
    Error
).then(() => {
    // ...
});
```

`error`는 문자열이 될 수 없습니다. 두 번째 인수로 문자열이 제공되면, `error`가 생략된 것으로 간주하고 문자열이 `message`로 사용됩니다. 이는 쉽게 놓칠 수 있는 실수를 유발할 수 있습니다. 두 번째 인수로 문자열을 사용하는 경우 [`assert.throws()`](https://nodejs.org/docs/latest/api/assert.html#assertthrowsfn-error-message)의 예제를 주의 깊게 읽어보세요.


### `assert.strictEqual(actual, expected[, message])`

- `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

`actual`과 `expected` 매개변수가 [`Object.is()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is)를 통해 엄격하게 동일한지 테스트합니다.

```javascript
import assert from 'node:assert/strict';

assert.strictEqual(1, 2);
// AssertionError [ERR_ASSERTION]: Expected inputs to be strictly equal:
//
// 1 !== 2

assert.strictEqual(1, 1);
// OK

assert.strictEqual('Hello foobar', 'Hello World!');
// AssertionError [ERR_ASSERTION]: Expected inputs to be strictly equal:
// + actual - expected
//
// + 'Hello foobar'
// - 'Hello World!'
// ^

const apples = 1;
const oranges = 2;
assert.strictEqual(apples, oranges, `apples ${apples} !== oranges ${oranges}`);
// AssertionError [ERR_ASSERTION]: apples 1 !== oranges 2

assert.strictEqual(1, '1', new TypeError('Inputs are not identical'));
// TypeError: Inputs are not identical
```

값이 엄격하게 동일하지 않으면, `message` 매개변수 값으로 설정된 `message` 속성을 가진 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다. `message` 매개변수가 정의되지 않았다면, 기본 오류 메시지가 할당됩니다. `message` 매개변수가 [`Error`](https://nodejs.org/docs/latest/api/errors.html#class-error)의 인스턴스라면, [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror) 대신 해당 오류가 발생합니다.


### `assert.throws(fn[, error][, message])`

- `fn` [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function)
- `error` [`<RegExp>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) | [`<Function>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) | [`<Object>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)
- `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type)

`assert.throws`는 함수 `fn`이 에러를 던질 것으로 예상합니다.

`error`가 지정된 경우, `error`는 [`Class`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes), [`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), 검증 함수, 각 속성이 엄격한 깊은 동등성(strict deep equality)으로 테스트되는 검증 객체, 또는 `message`와 `name` 속성을 포함한 모든 속성이 엄격한 깊은 동등성으로 테스트되는 에러 인스턴스가 될 수 있습니다. 객체를 사용할 때, 문자열 속성을 검증하기 위해 정규 표현식을 사용할 수도 있습니다. 아래 예제를 참고하세요.

`message`가 지정된 경우, `fn` 호출이 에러를 던지지 않거나 에러 검증이 실패할 때 `AssertionError`에 제공된 메시지에 추가됩니다.

커스텀 검증 객체/에러 인스턴스:

```js
import assert from 'node:assert/strict';

const err = new TypeError('Wrong value');
err.code = 404;
err.foo = 'bar';
err.info = {
    nested: true,
    baz: 'text',
};
err.reg = /abc/i;

assert.throws(
    () => {
        throw err;
    },
    {
        name: 'TypeError',
        message: 'Wrong value',
        info: {
            nested: true,
            baz: 'text',
        },
        // 검증 객체의 속성만 테스트됩니다.
        // 중첩 객체를 사용할 경우 모든 속성이 존재해야 합니다.
        // 그렇지 않으면 검증이 실패합니다.
    }
);

// 에러 속성을 검증하기 위해 정규 표현식 사용:
assert.throws(
    () => {
        throw err;
    },
    {
        // `name`과 `message` 속성은 문자열이며, 정규 표현식을 사용하여
        // 문자열과 매치됩니다. 매치되지 않으면 에러가 발생합니다.
        name: /^TypeError$/,
        message: /Wrong/,
        foo: 'bar',
        info: {
            nested: true,
            // 중첩 속성에는 정규 표현식을 사용할 수 없습니다!
            baz: 'text',
        },
        // `reg` 속성은 정규 표현식을 포함하며, 검증 객체에 동일한 정규 표현식이
        // 포함된 경우에만 통과합니다.
        reg: /abc/i,
    }
);

// `message`와 `name` 속성이 다르기 때문에 실패:
assert.throws(
    () => {
        const otherErr = new Error('Not found');
        // `err`의 모든 열거 가능한 속성을 `otherErr`에 복사합니다.
        for (const [key, value] of Object.entries(err)) {
            otherErr[key] = value;
        }
        throw otherErr;
    },
    // 에러를 검증 객체로 사용할 때, 에러의 `message`와 `name` 속성도 검사됩니다.
    err
);
```

생성자를 사용하여 `instanceof` 검증:

```js
import assert from 'node:assert/strict';

assert.throws(
    () => {
        throw new Error('Wrong value');
    },
    Error
);
```

[`RegExp`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions)를 사용하여 에러 메시지 검증:

정규 표현식을 사용하면 에러 객체에 `.toString`이 실행되며, 따라서 에러 이름도 포함됩니다.

```js
import assert from 'node:assert/strict';

assert.throws(
    () => {
        throw new Error('Wrong value');
    },
    /^Error: Wrong value$/
);
```

커스텀 에러 검증:

함수는 모든 내부 검증이 통과했음을 나타내기 위해 `true`를 반환해야 합니다. 그렇지 않으면 [`AssertionError`](https://nodejs.org/docs/latest/api/assert.html#class-assertassertionerror)가 발생합니다.

```js
import assert from 'node:assert/strict';

assert.throws(
    () => {
        throw new Error('Wrong value');
    },
    (err) => {
        assert(err instanceof Error);
        assert(/value/.test(err));
        // 검증 함수에서 `true` 이외의 값을 반환하지 마세요.
        // 대신, 특정 검증이 실패한 경우 에러를 던지고 가능한 한 많은 디버깅 정보를 추가하세요.
        return true;
    },
    'unexpected error'
);
```

`error`는 문자열이 될 수 없습니다. 두 번째 인자로 문자열이 제공되면 `error`가 생략된 것으로 간주되고 문자열은 `message`로 사용됩니다. 이는 실수하기 쉬운 상황을 초래할 수 있습니다. 던져진 에러 메시지와 동일한 메시지를 사용하면 `ERR_AMBIGUOUS_ARGUMENT` 에러가 발생합니다. 두 번째 인자로 문자열을 사용할 경우 아래 예제를 주의 깊게 읽어보세요:

```js
import assert from 'node:assert/strict';

function throwingFirst() {
    throw new Error('First');
}

function throwingSecond() {
    throw new Error('Second');
}

function notThrowing() {}

// 두 번째 인자가 문자열이고 입력 함수가 에러를 던졌습니다.
// 첫 번째 경우는 입력 함수가 던진 에러 메시지와 일치하지 않으므로 에러가 발생하지 않습니다!
assert.throws(throwingFirst, 'Second');

// 다음 예제에서는 메시지가 에러 메시지와 동일하며, 사용자가 실제로 에러 메시지와
// 매치하려고 했는지 명확하지 않기 때문에 Node.js는 `ERR_AMBIGUOUS_ARGUMENT` 에러를 던집니다.
assert.throws(throwingSecond, 'Second'); // TypeError [ERR_AMBIGUOUS_ARGUMENT]

// 문자열은 함수가 에러를 던지지 않을 경우에만 (메시지로) 사용됩니다:
assert.throws(notThrowing, 'Second'); // AssertionError [ERR_ASSERTION]: Missing expected exception: Second

// 에러 메시지와 매치하려면 대신 이렇게 하세요:
// 에러 메시지가 일치하므로 에러가 발생하지 않습니다.
assert.throws(throwingSecond, /Second$/);

// 에러 메시지가 일치하지 않으면 AssertionError가 발생합니다.
assert.throws(throwingFirst, /Second$/); // AssertionError [ERR_ASSERTION]
```

혼동을 일으키기 쉬운 표기법이므로 두 번째 인자로 문자열을 사용하지 마세요.


### `assert.partialDeepStrictEqual(actual, expected[, message])`[#](https://nodejs.org/docs/latest/api/assert.html#assertpartialdeepstrictequalactual-expected-message)

추가된 버전: v23.4.0

-   `actual` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `expected` [`<any>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types)
-   `message` [`<string>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type) | [`<Error>`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

[`assert.partialDeepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertpartialdeepstrictequalactual-expected-message)은 `actual`과 `expected` 매개변수를 깊은 비교를 통해 동등성을 검증합니다. 이때 `expected` 매개변수의 모든 속성이 `actual` 매개변수에 동일한 값으로 존재하는지 확인하며, 타입 강제 변환을 허용하지 않습니다. [`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)과의 주요 차이점은 [`assert.partialDeepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertpartialdeepstrictequalactual-expected-message)이 `actual` 매개변수의 모든 속성이 `expected` 매개변수에 존재할 것을 요구하지 않는다는 점입니다. 이 메서드는 [`assert.deepStrictEqual()`](https://nodejs.org/docs/latest/api/assert.html#assertdeepstrictequalactual-expected-message)과 동일한 테스트 케이스를 통과해야 하며, 그 상위 집합으로 동작합니다.

```js
import assert from 'node:assert';

assert.partialDeepStrictEqual({ a: 1, b: 2 }, { a: 1, b: 2 }); // 통과
assert.partialDeepStrictEqual({ a: { b: { c: 1 } } }, { a: { b: { c: 1 } } }); // 통과
assert.partialDeepStrictEqual({ a: 1, b: 2, c: 3 }, { a: 1, b: 2 }); // 통과
assert.partialDeepStrictEqual(new Set(['value1', 'value2']), new Set(['value1', 'value2'])); // 통과
assert.partialDeepStrictEqual(new Map([['key1', 'value1']]), new Map([['key1', 'value1']])); // 통과
assert.partialDeepStrictEqual(new Uint8Array([1, 2, 3]), new Uint8Array([1, 2, 3])); // 통과
assert.partialDeepStrictEqual(/abc/, /abc/); // 통과
assert.partialDeepStrictEqual([{ a: 5 }, { b: 5 }], [{ a: 5 }]); // 통과
assert.partialDeepStrictEqual(new Set([{ a: 1 }, { b: 1 }]), new Set([{ a: 1 }])); // 통과
assert.partialDeepStrictEqual(new Date(0), new Date(0)); // 통과
assert.partialDeepStrictEqual({ a: 1 }, { a: 1, b: 2 }); // AssertionError 발생
assert.partialDeepStrictEqual({ a: 1, b: '2' }, { a: 1, b: 2 }); // AssertionError 발생
assert.partialDeepStrictEqual({ a: { b: 2 } }, { a: { b: '2' } }); // AssertionError 발생
```


